---

- hosts: F5
  gather_facts: false
  connection: local

  vars:
    command_list:
        - show sys version
#        - list auth user | grep auth
        - show sys clock
        - list /ltm data-group internal CName_DG499
  tasks:
  - name: Run command
    bigip_command:
      provider:
          server: myf5
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: 443
          validate_certs: false
      commands: "{{ command_list }}"

      chdir: B_3333
    register: result
  - name: Check Stuff
    debug: 
      msg: "{{result.stdout_lines}}"

  - name: "Put all output together into one nice text file"
    template:
        src: template.j2
        dest: "/tmp/F5_details.txt"
        
  - name: Ansible zip file with path example
    archive:
      path: /tmp/F5_details.txt
      dest: /tmp/report-test.zip
      format: zip
      remove: true
      
  - name: set pw
    ansible.builtin.shell: zip --password 11 /tmp/test.zip /tmp/report-test.zip
      


