---

- name: F5- Update Cname List
  hosts: F5
  connection: local
  gather_facts: false

  vars:
    cname_list:
        - CName_DG499


  tasks:
    
  - name: Update an existing external data group of strings
    bigip_data_group:
      chdir: B_3999
      name: "{{ cname_list }}"
      external: yes
      records:
        - key: bla bala
          value: "test bla"
        - key: blaaaaaaaaaaaaa
          value: "testt balaaa"
      provider:
        password: "{{ ansible_password }}"
        server: myf5
        user: "{{ ansible_user }}"
 #       transport: cli
    delegate_to: localhost

    register: result
  - debug: msg="{{result.stdout_lines}}"
    delegate_to: localhost
