---

- name: F5- Update Cname List
  hosts: f5taas
  connection: local
  gather_facts: false

  vars:
    cname_list:
        - DG_INREWN_HTTS001_Valid_Cert_CName
        - Blsss
        - Another list name

  tasks:
    
  - name: Update an existing external data group of strings
    bigip_data_group:
      chdir: B_4999
      name: "{{ cname_list }}"
      external: yes
      records:
        - key: bla bala
          value: "test bla"
        - key: blaaaaaaaaaaaaa
          value: "testt balaaa"
      provider:
        password: password: "{{ _PASSWD }}"
        server: prtcorlbs03.svns.net.nz
        user: "{{ _USER }}"
        transport: cli
    delegate_to: localhost

    register: result
  - debug: msg="{{result.stdout_lines}}"
    delegate_to: localhost
